//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ITestSoap11Binding", Namespace="http://web")]
public partial class ITest : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback sendOperationCompleted;
    
    /// <remarks/>
    public ITest() {
        this.Url = "http://localhost:8080/axis2/services/ITest.ITestHttpSoap11Endpoint/";
    }
    
    /// <remarks/>
    public event sendCompletedEventHandler sendCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:send", RequestNamespace="http://web", ResponseNamespace="http://web", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
    public Animal send([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Animal args0) {
        object[] results = this.Invoke("send", new object[] {
                    args0});
        return ((Animal)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginsend(Animal args0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("send", new object[] {
                    args0}, callback, asyncState);
    }
    
    /// <remarks/>
    public Animal Endsend(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Animal)(results[0]));
    }
    
    /// <remarks/>
    public void sendAsync(Animal args0) {
        this.sendAsync(args0, null);
    }
    
    /// <remarks/>
    public void sendAsync(Animal args0, object userState) {
        if ((this.sendOperationCompleted == null)) {
            this.sendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendOperationCompleted);
        }
        this.InvokeAsync("send", new object[] {
                    args0}, this.sendOperationCompleted, userState);
    }
    
    private void OnsendOperationCompleted(object arg) {
        if ((this.sendCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sendCompleted(this, new sendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model/xsd")]

public partial class Animal {
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private string typeField;
   
    private int waightField;
    
    private bool waightFieldSpecified;

    public Animal(int v1, string v2, int v3)
    {
        this.idField = v1;
        this.typeField = v2;
        this.waightField = v3;
        this.waightFieldSpecified = true;
        this.idFieldSpecified = true;
    }

    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public int waight {
        get {
            return this.waightField;
        }
        set {
            this.waightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool waightSpecified {
        get {
            return this.waightFieldSpecified;
        }
        set {
            this.waightFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void sendCompletedEventHandler(object sender, sendCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Animal Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Animal)(this.results[0]));
        }
    }
}
